name: uap_python3_v1.0
channels:
  - biobuilds
  - bioinfo
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - adapterremoval=2.3.1
  - alsa-lib=1.2.3
  - appdirs=1.4.4
  - atk=2.36.0
  - atk-1.0=2.36.0
  - bowtie2=2.4.2
  - bwa=0.7.17
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.11.8
  - cairo=1.16.0
  - certifi=2020.11.8
  - chrpath=0.16
  - conda=4.8.4
  - conda-build=3.20.3 
  - cufflinks=2.2.1
  - curl=7.71.1
  - cutadapt=2.10
  - cycler=0.10.0
  - dbus=1.13.6
  - distlib=0.3.1
  - dnaio=0.4.4
  - expat=2.2.9
  - fastqc=0.11.4
  - fastx_toolkit=0.0.14
  - filelock=3.0.12
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.0
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.66.2
  - gnuplot=5.2.7
  - gobject-introspection=1.66.1
  - graphite2=1.3.13
  - graphviz=2.42.3
  - gsl=2.6
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gtk2=2.24.32
  - harfbuzz=2.4.0
  - hdf5=1.10.5
  - hisat2=2.2.1
  - htseq=0.12.4
  - htslib=1.9
  - icu=64.2
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - importlib_resources=1.5.0
  - isa-l=2.30.0
  - jemalloc=5.2.1
  - jpeg=9d
  - kallisto=0.46.2
  - kiwisolver=1.3.1
  - krb5=1.17.1
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libdeflate=1.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgd=2.2.5
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.2
  - libgomp=9.3.0
  - libgtextutils=0.7
  - libiconv=1.16
  - liblapack=3.9.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - macs2=2.2.7.1
  - matplotlib-base=3.3.3
  - mysql-connector-c=6.1.11
  - ncurses=6.1
  - numpy=1.19.4
  - olefile=0.46
  - openblas=0.3.12
  - openjdk=11.0.8
  - openssl=1.1.1h
  - pango=1.42.4
  - pcre=8.44
  - perl=5.26.2
  - perl-gd=2.71
  - perl-gdgraph=1.54
  - perl-gdgraph-histogram=1.1
  - perl-gdtextutil=0.86
  - perl-perlio-gzip=0.20
  - picard=2.18.7
  - pigz=2.3.4
  - pillow=8.0.1
  - pip=20.2.4
  - pixman=0.38.0
  - preseq=2.0.3
  - pthread-stubs=0.4
  - pyparsing=2.4.7
  - pysam=0.16.0.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - qt=5.9.7
  - readline=8.0
  - salmon=1.3.0
  - samtools=1.9
  - segemehl=0.3.4
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.32.3
  - star=2.7.6a
  - stringtie=2.1.2
  - tbb=2020.2
  - tk=8.6.10
  - tornado=6.1
  - ucsc-fetchchromsizes=377
  - virtualenv=20.0.20
  - wheel=0.35.1
  - xopen=1.0.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxpm=3.5.13
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.1.5
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
